version: '3.8'

services:
  company-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=172.31.21.77
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=company_db
      - JWT_SECRET=your_jwt_secret
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge