apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  # Namespace removed for Argo CD flexibility
data:
  DB_HOST: "postgres-service"
  DB_USER: "postgres"
  DB_NAME: "company_dashboard"
  DB_PORT: "5432"
  
  # API URL is set to relative /api because Nginx handles the proxy.
  # This works for both local and production if accessed via Ingress.
  REACT_APP_API_URL: "/api"
