apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: company-app
data:
  DB_HOST: "postgres-service"
  DB_USER: "postgres"
  DB_NAME: "company_dashboard"
  DB_PORT: "5432"

  # the backend URL for the frontend build
  REACT_APP_API_URL: "http://backend-service:5000"
