apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  # Namespace removed for Argo CD flexibility
type: Opaque
data:
  # Base64 encoded "password"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DB_PASSWORD: cGFzc3dvcmQ=
