apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: company-app
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=        # "password" base64 encoded
  DB_PASSWORD: cGFzc3dvcmQ=              # backend expects this
