apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sahalht/argocd-three-tier-app
    targetRevision: HEAD
    path: k8s/3-tier-app
  destination:
    server: https://kubernetes.default.svc
    namespace: company-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
